added latex diff target (to be validated)

diff --git a/PaperMakefile/Makefile b/PaperMakefile/Makefile
--- a/PaperMakefile/Makefile
+++ b/PaperMakefile/Makefile
@@ -48,3 +48,23 @@ export:
 	echo "	"pdflatex ${BASENAME}.tex >> export/Makefile
 	echo .PHONY: ${BASENAME}.pdf >> export/Makefile
 
+
+
+with=NONE
+latexdiff:
+	@test ${with} '!=' NONE || (echo -n "\n\nPlease check you saved/commited everything and use something like \n    make latexdiff with=HEAD^\n\n"; false)
+	rm -rf latexdiff
+	mkdir latexdiff
+	git rev-parse --abbrev-ref HEAD  | sed 's@^refs/heads/@@g' > ,,latexdiff.br
+	test $$(cat ,,latexdiff.br) '!=' "HEAD"
+	git stash save "Before latexdiff"
+	git checkout ${with}
+	cp *.tex latexdiff/
+	cat ,,latexdiff.br | xargs git checkout
+	rm -f ,,latexdiff.br
+	(cd latexdiff && for i in $$(find -name \*.tex) ; do latexdiff $$i ../$$i > diff; yes | mv diff ../$$i; done)
+	make || (echo -n "\n\nCompilation of diff'ed latex failed.\nPlease fix it, make and do whatever you want with the pdf.\nTHEN, run:\n    git reset --hard ; git stash apply\n\n" ; false) 
+	mv ${BASENAME}.pdf latexdiff.pdf
+	git reset --hard
+	git stash apply
+
